# Generated by Django 5.2.15 on 2026-06-14 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clustering", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_target",
                    models.CharField(
                        choices=[
                            ("developer", "Developer"),
                            ("designer", "UI/UX Designer"),
                            ("business_analyst", "Business Analyst"),
                            ("manajemen", "Staf Manajemen"),
                        ],
                        max_length=20,
                    ),
                ),
                ("budget_min_idr", models.BigIntegerField()),
                ("budget_max_idr", models.BigIntegerField()),
                ("min_ram_gb", models.PositiveIntegerField()),
                ("min_processor_tier", models.PositiveSmallIntegerField()),
                ("min_storage_gb", models.PositiveIntegerField()),
                (
                    "storage_type",
                    models.CharField(
                        blank=True,
                        choices=[("SSD", "SSD"), ("HDD", "HDD")],
                        max_length=3,
                    ),
                ),
                (
                    "vga_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("integrated", "Integrated"),
                            ("dedicated", "Dedicated"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "min_screen_inch",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "min_battery_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("brand_preference", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("results", models.JSONField()),
                ("precision_at_k", models.FloatField()),
                ("k_value", models.PositiveSmallIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clustering.clustermodel",
                    ),
                ),
                (
                    "preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="recommender.preference",
                    ),
                ),
                (
                    "selected_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clustering.cluster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
