# Generated by Django 5.2.15 on 2026-06-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_laptop_sub_brand'),
        ('recommender', '0002_alter_preference_brand_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='sub_brand_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.subbrand'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='brand_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand'),
        ),
    ]
