# Generated by Django 5.2.15 on 2026-06-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClusterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("k_optimal", models.PositiveSmallIntegerField()),
                ("centroids", models.JSONField()),
                ("silhouette_score", models.FloatField()),
                ("wcss_list", models.JSONField()),
                ("silhouette_list", models.JSONField()),
                ("scaler_params", models.JSONField()),
                ("feature_order", models.JSONField()),
                (
                    "elbow_plot",
                    models.ImageField(blank=True, null=True, upload_to="plots/"),
                ),
                (
                    "silhouette_plot",
                    models.ImageField(blank=True, null=True, upload_to="plots/"),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.IntegerField()),
                ("interpretation", models.CharField(max_length=40)),
                ("centroid", models.JSONField()),
                ("member_count", models.PositiveIntegerField()),
                ("summary", models.JSONField(default=dict)),
                (
                    "cluster_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clusters",
                        to="clustering.clustermodel",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
            },
        ),
    ]
