# Generated by Django 5.2.15 on 2026-06-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clustermodel',
            name='elbow_plot',
        ),
        migrations.RemoveField(
            model_name='clustermodel',
            name='silhouette_plot',
        ),
    ]
