# Generated by Django 5.2.15 on 2026-06-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=120)),
                ("processor", models.CharField(max_length=120)),
                (
                    "processor_tier",
                    models.PositiveSmallIntegerField(
                        help_text="Ordinal performance tier 1-10"
                    ),
                ),
                ("ram_gb", models.PositiveIntegerField()),
                ("storage_gb", models.PositiveIntegerField()),
                (
                    "storage_type",
                    models.CharField(
                        choices=[("SSD", "SSD"), ("HDD", "HDD")],
                        default="SSD",
                        max_length=3,
                    ),
                ),
                ("vga", models.CharField(max_length=80)),
                (
                    "vga_type",
                    models.CharField(
                        choices=[
                            ("integrated", "Integrated"),
                            ("dedicated", "Dedicated"),
                        ],
                        default="integrated",
                        max_length=10,
                    ),
                ),
                ("screen_inch", models.DecimalField(decimal_places=1, max_digits=4)),
                ("battery_hours", models.DecimalField(decimal_places=1, max_digits=4)),
                ("price_idr", models.BigIntegerField()),
                ("cluster_label", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["brand", "model"],
            },
        ),
    ]
