# Generated by Django 5.2.15 on 2026-06-22 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_gpu_processor_remove_laptop_processor_tier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_brands', to='catalog.brand')),
            ],
            options={
                'verbose_name': 'Sub Brand',
                'verbose_name_plural': 'Sub Brands',
                'ordering': ['brand', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
