# Generated by Django 5.2.15 on 2026-06-22 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_subbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='sub_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptops', to='catalog.subbrand'),
        ),
    ]
